import { lazy, Suspense, useMemo, useState } from "react";
import type { LibraryItem, PackingPlan, Suitcase, TripSummary } from "../contracts";
import { PlanMetrics } from "../components/PlanMetrics";

const PackingViewer = lazy(() => import("../components/PackingViewer").then(module => ({ default: module.PackingViewer })));

export function PlanPage({ plan, summary, catalog, stale, busy, onReplan }: { plan: PackingPlan; summary: TripSummary; catalog: LibraryItem[]; stale: boolean; busy: boolean; onReplan: (suitcase: Suitcase) => void }) {
  const [engineering, setEngineering] = useState(false);
  const [draft, setDraft] = useState(summary.trip.suitcase);
  const byId = useMemo(() => new Map(catalog.map(item => [item.id, item])), [catalog]);
  const excludedIds = useMemo(() => new Set(plan.excluded_instance_ids), [plan.excluded_instance_ids]);
  const snapshotTrip = plan.snapshot?.trip ?? summary.trip;
  const snapshotCatalog = plan.snapshot?.item_snapshots ?? catalog;
  const missingMandatory = snapshotTrip.items.flatMap(entry => entry.instances.filter(instance => instance.must_pack && excludedIds.has(instance.id)).map(instance => snapshotCatalog.find(item => item.id === entry.item_id)?.name ?? "Item"));
  const update = (field: "width" | "height" | "depth" | "baggage_limit_g", value: string) => setDraft(current => field === "baggage_limit_g" ? { ...current, baggage_limit_g: Number(value) } : { ...current, internal_dimensions_mm: { ...current.internal_dimensions_mm, [field]: Number(value) } });
  return <section className="plan-page">
    {stale && <p className="notice warning" role="status">This result is outdated while your replan is running. It remains visible for comparison.</p>}
    <Suspense fallback={<section className="packing-viewer" aria-live="polite">Loading the validated 3D viewer…</section>}><PackingViewer plan={plan} suitcase={snapshotTrip.suitcase} catalog={snapshotCatalog} /></Suspense>
    <PlanMetrics plan={plan} />
    <section className="plan-instructions"><div className="viewer-heading"><div><p className="eyebrow">PACKING INSTRUCTIONS</p><h2>Place items in order</h2></div><span>{plan.instructions.length} validated steps</span></div>{missingMandatory.length > 0 && <p className="notice error"><strong>Missing mandatory items: {missingMandatory.join(", ")}.</strong> Edit suitcase dimensions, clearance, or baggage limit and replan.</p>}{plan.instructions.length ? <ol>{plan.instructions.map(instruction => <li key={instruction.instance_id}><strong>{instruction.number}. {instruction.item_name} · copy {instruction.copy_number}</strong><span>{instruction.destination} · {instruction.orientation_label}{instruction.handling_note ? ` · ${instruction.handling_note}` : ""}</span></li>)}</ol> : <p className="notice warning">No validated instructions are available for this result.</p>}{plan.exclusion_evidence.length > 0 && <div className="exclusions"><h3>Excluded items</h3>{plan.exclusion_evidence.map(evidence => <p key={evidence.instance_id}>{byId.get(summary.trip.items.flatMap(entry => entry.instances).find(instance => instance.id === evidence.instance_id)?.item_id ?? "")?.name ?? "Item"}: {evidence.detail}</p>)}</div>}<p className="balance-note">Center of mass is an approximate mass-at-box-center model, not a physical measurement.</p></section>
    <section className="replan-card"><div><p className="eyebrow">QUICK REPLAN</p><h2>Test a suitcase constraint</h2><p>Previous results stay visible and are marked outdated until the new validator-approved plan arrives.</p></div><div className="quick-edits"><label>Width (mm)<input type="number" min="1" value={draft.internal_dimensions_mm.width} onChange={event => update("width", event.target.value)} /></label><label>Height (mm)<input type="number" min="1" value={draft.internal_dimensions_mm.height} onChange={event => update("height", event.target.value)} /></label><label>Depth (mm)<input type="number" min="1" value={draft.internal_dimensions_mm.depth} onChange={event => update("depth", event.target.value)} /></label><label>Baggage limit (g)<input type="number" min="1" value={draft.baggage_limit_g} onChange={event => update("baggage_limit_g", event.target.value)} /></label></div><button className="primary inline" disabled={busy} onClick={() => onReplan(draft)}>Replan with these constraints</button></section>
    <details className="engineering-view" open={engineering} onToggle={event => setEngineering((event.currentTarget as HTMLDetailsElement).open)}><summary>Engineering details</summary><div className="engineering-grid"><pre>{JSON.stringify({ solver_version: plan.solver_version, snapshot_id: plan.snapshot_id, snapshot_versions: plan.snapshot && { geometry: plan.snapshot.geometry_version, handling: plan.snapshot.handling_confirmation_version, seed: plan.snapshot.seed }, expanded_boxes: plan.snapshot?.expanded_boxes, diagnostics: plan.diagnostics, validation: plan.validation }, null, 2)}</pre><p>Placements are validated against the immutable snapshot’s effective padded boxes. Meshes are visual provenance only; the typed validator remains authoritative.</p></div></details>
  </section>;
}
