import { useEffect, useMemo, useRef, useState } from "react";
import { api } from "../api";
import type { LibraryItem, PackingPlan, Suitcase, TripItemRequest, TripPreflight, TripSummary } from "../contracts";
import { SuitcaseForm } from "../components/SuitcaseForm";
import { PlanPage } from "./PlanPage";

const defaultSuitcase: Suitcase = { id: crypto.randomUUID(), name: "Carry-on", internal_dimensions_mm: { width: 550, height: 350, depth: 230 }, empty_weight_g: 2500, baggage_limit_g: 10000, clearance_mm: 8, display_length_unit: "mm", display_weight_unit: "g" };

export function TripBuilderPage({ selectedIds }: { selectedIds: string[] }) {
  const [catalog, setCatalog] = useState<LibraryItem[]>([]); const [summary, setSummary] = useState<TripSummary | null>(null);
  const [name, setName] = useState("My trip"); const [suitcase, setSuitcase] = useState<Suitcase>(defaultSuitcase);
  const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const [plan, setPlan] = useState<PackingPlan | null>(null);
  const [preflight, setPreflight] = useState<TripPreflight | null>(null);
  const [planStale, setPlanStale] = useState(false);
  const requestVersion = useRef(0);
  const byId = useMemo(() => new Map(catalog.map(item => [item.id, item])), [catalog]);
  useEffect(() => {
    void api.library().then(setCatalog);
    if (selectedIds.length) return;
    const saved = localStorage.getItem("packright-active-trip");
    if (saved) void api.getTrip(saved).then(next => { setSummary(next); setName(next.trip.name); setSuitcase(next.trip.suitcase); }).catch(() => localStorage.removeItem("packright-active-trip"));
  }, [selectedIds]);
  useEffect(() => { if (summary) void api.preflight(summary.trip.id).then(setPreflight).catch(() => setPreflight(null)); }, [summary]);
  const create = async () => {
    setBusy(true); setMessage(null);
    try {
      const next = await api.createTrip(name, suitcase, selectedIds);
      localStorage.setItem("packright-active-trip", next.trip.id); setSummary(next);
    } catch (error) { setMessage(error instanceof Error ? error.message : "Could not create trip."); } finally { setBusy(false); }
  };
  const setItem = async (request: TripItemRequest) => { if (!summary) return; try { setSummary(await api.setTripItem(summary.trip.id, request)); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not update item."); } };
  const setQuantity = (entry: TripSummary["trip"]["items"][number], raw: string) => { if (raw === "") return; const quantity = Number(raw); if (!Number.isInteger(quantity) || quantity < 0) return; const first = entry.instances[0]; if (first) void setItem({ item_id: entry.item_id, quantity, priority_stars: first.priority_stars, must_pack: first.must_pack, access_preference: first.access_preference }); };
  const saveSuitcase = async () => { if (!summary) return; setBusy(true); try { setSummary(await api.updateTrip(summary.trip.id, name, suitcase)); setMessage("Trip and suitcase saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save suitcase."); } finally { setBusy(false); } };
  const waitForPlan = async (jobId: string, version: number) => { for (let attempt = 0; attempt < 80; attempt += 1) { const job = await api.getPlanJob(jobId); if (version !== requestVersion.current) return null; if (job.status === "completed" && job.plan_id) return api.getPlan(job.plan_id); if (job.status === "failed" || job.status === "retryable") throw new Error(job.error_message ?? "The plan operation failed. Retry it from recovery status."); await new Promise(resolve => window.setTimeout(resolve, 150)); } throw new Error("The plan is still running. Reopen this plan job to resume it."); };
  const pack = async (replanSuitcase = suitcase) => { if (!summary) return; const version = ++requestVersion.current; setBusy(true); setPlanStale(Boolean(plan)); setMessage(plan ? "Replanning with the new suitcase snapshot…" : "Creating an immutable trip snapshot and queuing the plan…"); try { let job; if (plan) { job = await api.replanJob(plan.id, replanSuitcase, name, `replan-${crypto.randomUUID()}`); } else { const saved = await api.updateTrip(summary.trip.id, name, replanSuitcase); if (version !== requestVersion.current) return; setSummary(saved); job = await api.createPlanJob(saved.trip.id, 7, `plan-${crypto.randomUUID()}`); } const nextPlan = await waitForPlan(job.id, version); if (!nextPlan || version !== requestVersion.current) return; setPlan(nextPlan); setPlanStale(false); const refreshed = await api.getTrip(nextPlan.trip_id); setSummary(refreshed); window.history.pushState({}, "", `/plans/${nextPlan.id}`); setMessage(nextPlan.state === "feasible" ? "A validator-approved packing plan was saved." : nextPlan.state === "infeasible" ? "A hard mandatory constraint proves this trip infeasible." : "The bounded spatial search did not find a valid arrangement."); } catch (error) { if (version === requestVersion.current) setMessage(error instanceof Error ? error.message : "Could not solve this trip. Your prior plan remains selected."); } finally { if (version === requestVersion.current) setBusy(false); } };
  return <main className="trip-page"><header className="section-header"><div><p className="eyebrow">TRIP BUILDER</p><h1>Configure the load</h1><p>Quantities and constraints here do not change your library defaults.</p></div></header>
    {!summary ? <section className="trip-start"><label>Trip name<input value={name} onChange={event => setName(event.target.value)} /></label><p>{selectedIds.length} selected library items</p><button className="primary inline" disabled={busy || !selectedIds.length} onClick={create}>Create trip</button>{!selectedIds.length && <p className="notice warning">Select ready items from the library first.</p>}</section> : <>
      <section className="trip-items"><h2>Selected items</h2>{summary.trip.items.map(entry => { const item = byId.get(entry.item_id); const first = entry.instances[0]; return <article key={entry.item_id}><div><strong>{item?.name ?? "Saved item"}</strong><small>{item?.weight_g.toLocaleString()} g each</small></div><label>Quantity<input type="number" min="0" max="24" value={entry.instances.length} onChange={event => setQuantity(entry, event.target.value)} /></label><label>Trip priority<select value={first.priority_stars} onChange={event => void setItem({ item_id: entry.item_id, quantity: entry.instances.length, priority_stars: Number(event.target.value) as TripItemRequest["priority_stars"], must_pack: first.must_pack, access_preference: first.access_preference })}>{[1,2,3,4,5].map(value => <option value={value} key={value}>{value} stars</option>)}</select></label><label>Access<select value={first.access_preference ?? "normal"} onChange={event => void setItem({ item_id: entry.item_id, quantity: entry.instances.length, priority_stars: first.priority_stars, must_pack: first.must_pack, access_preference: event.target.value as TripItemRequest["access_preference"] })}><option value="quick">Quick access</option><option value="normal">Normal</option><option value="buried_ok">Buried okay</option></select></label><label className="check"><input type="checkbox" checked={first.must_pack} onChange={event => void setItem({ item_id: entry.item_id, quantity: entry.instances.length, priority_stars: first.priority_stars, must_pack: event.target.checked, access_preference: first.access_preference })} /> Must pack</label></article>; })}</section>
      <section className="trip-metrics"><div><small>Requested items</small><strong>{summary.requested_item_weight_g.toLocaleString()} g</strong></div><div><small>Available item weight</small><strong>{summary.available_item_weight_g.toLocaleString()} g</strong></div><div><small>Total utility</small><strong>{summary.total_utility}</strong></div></section>
      {preflight && <section className="preflight-card" aria-live="polite"><strong>Advisory preflight</strong><span>{preflight.requested_instances} instances · {preflight.requested_weight_g.toLocaleString()} g requested · {preflight.baggage_remaining_g.toLocaleString()} g baggage remaining</span>{preflight.actionable_messages.map(message => <p className="notice warning" key={message}>{message}</p>)}</section>}
      {summary.warnings.map(warning => <p className="notice warning" key={warning}>{warning === "requested_items_overweight" ? "Requested items exceed the available baggage weight." : warning.startsWith("oversize:") ? "An item has no orientation that fits this suitcase." : "A selected item is missing packing data."}</p>)}
      <SuitcaseForm suitcase={suitcase} onChange={setSuitcase} availableWeight={suitcase.baggage_limit_g - suitcase.empty_weight_g} />
      <div className="trip-pack-actions"><button className="secondary" disabled={busy} onClick={saveSuitcase}>Save trip changes</button><button className="primary" disabled={busy || !summary.trip.items.length} onClick={() => void pack()}>{plan ? "Repack with current constraints" : "Pack these items"}</button></div>
      {plan && <><section className={`plan-result ${plan.state}`}><div><p className="eyebrow">PACKING RESULT</p><h2>{plan.state.replaceAll("_", " ")}</h2></div><div className="trip-metrics"><div><small>Packed instances</small><strong>{plan.placements.length}</strong></div><div><small>Runtime</small><strong>{plan.runtime_ms.toFixed(0)} ms</strong></div><div><small>Search mode</small><strong>{plan.diagnostics?.heuristic ? "Bounded heuristic" : "Exact selection"}</strong></div></div>{plan.validation?.valid && <p className="validator-pass">✓ Independently validated: bounds, collisions, orientations, support, sequence, and weight.</p>}{plan.exclusion_evidence.map(evidence => <p className="notice warning" key={evidence.instance_id}>{evidence.detail}</p>)}</section>{summary && <PlanPage plan={plan} summary={summary} catalog={catalog} stale={planStale} busy={busy} onReplan={nextSuitcase => void pack(nextSuitcase)} />}</>}
    </>}{message && <p className="notice">{message}</p>}</main>;
}
